services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hangman-net

  backend:
    build: ./backend
    container_name: hangman-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - hangman-net

volumes:
  mongo-data:

networks:
  hangman-net:

